try:
    a = []
    print(a[1])
except Exception as erro:
    print('Erro qualquer')
